apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-project
    labels:
      app: devops-project
spec:
    selector:
      matchLabels:
        app: devops-project
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          app: devops-project
      spec:
        containers:
        - image: nediabenrekaya/devops-project
          name: devops-project-1
          ports:
          - containerPort: 3000
---     
apiVersion: v1
  kind: Service
  metadata:
    name: devops-project-service
    labels:
      app: devops-project
  spec:
    ports:
      - port: 3000
    selector:
      app: devops-project-1
    type: NodePort
  
